import {
  BarChart3,
  FileText,
  Receipt,
  BookOpen,
  Users,
  TrendingUp,
  ShieldCheck,
  Cpu,
  Landmark,
  Banknote,
  Monitor,
  Award,
  type LucideIcon,
} from "lucide-react";

export type CourseCategory = "Accounting" | "Taxation" | "Compliance" | "Advanced";

export interface Course {
  id: string;
  title: string;
  slug: string;
  badge: string | null;
  icon: LucideIcon;
  level: string;
  duration: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewCount: number;
  description: string;
  gradient: string;
  topics: string[];
  category: CourseCategory;
}

export const courses: Course[] = [
  {
    id: "c1",
    title: "Tally Prime Complete Mastery",
    slug: "tally-prime-complete-mastery",
    badge: "BESTSELLER",
    icon: BarChart3,
    level: "Beginner → Expert",
    duration: "3 Months",
    price: 7499,
    originalPrice: 12000,
    rating: 4.9,
    reviewCount: 142,
    description: "From basic vouchers to advanced inventory management — become the Tally expert every company is searching for.",
    gradient: "linear-gradient(135deg, #16A34A, #22C55E)",
    topics: ["Voucher Entry", "Bank Reconciliation", "GST in Tally", "Payroll", "Inventory", "Reports"],
    category: "Accounting",
  },
  {
    id: "c2",
    title: "GST Filing & Compliance Expert",
    slug: "gst-filing-compliance-expert",
    badge: "HOT",
    icon: FileText,
    level: "Intermediate",
    duration: "6 Weeks",
    price: 5999,
    originalPrice: 8999,
    rating: 4.8,
    reviewCount: 98,
    description: "Navigate India's GST labyrinth with confidence. File GSTR-1, GSTR-3B, handle ITC claims, and crush audits.",
    gradient: "linear-gradient(135deg, #0D4A26, #16A34A)",
    topics: ["GST Registration", "GSTR-1 & 3B Filing", "ITC Computation", "E-Way Bill", "GST Audits", "Annual Returns"],
    category: "Taxation",
  },
  {
    id: "c3",
    title: "Income Tax & ITR Filing Pro",
    slug: "income-tax-itr-filing-pro",
    badge: "NEW",
    icon: Receipt,
    level: "Beginner",
    duration: "8 Weeks",
    price: 4999,
    originalPrice: 8000,
    rating: 4.9,
    reviewCount: 64,
    description: "Master income tax computation, deductions under 80C-80U, and file ITR forms 1 through 7 with zero errors.",
    gradient: "linear-gradient(135deg, #166534, #22C55E)",
    topics: ["Tax Slabs & Computation", "80C-80U Deductions", "ITR-1 to ITR-7", "TDS Returns", "Advance Tax", "Tax Planning"],
    category: "Taxation",
  },
  {
    id: "c4",
    title: "Financial Accounting & Reporting",
    slug: "financial-accounting-reporting",
    badge: null,
    icon: BookOpen,
    level: "Intermediate",
    duration: "4 Months",
    price: 9999,
    originalPrice: 15000,
    rating: 4.7,
    reviewCount: 112,
    description: "Build and read Profit & Loss, Balance Sheet, Cash Flow Statements like a seasoned finance professional.",
    gradient: "linear-gradient(135deg, #15803D, #4ADE80)",
    topics: ["Journal Entries", "Ledgers", "Trial Balance", "P&L Statements", "Balance Sheets", "Cash Flow Analysis"],
    category: "Accounting",
  },
  {
    id: "c5",
    title: "Payroll & HR Compliance",
    slug: "payroll-hr-compliance",
    badge: null,
    icon: Users,
    level: "Beginner",
    duration: "4 Weeks",
    price: 3499,
    originalPrice: 5500,
    rating: 4.8,
    reviewCount: 85,
    description: "Process salaries, PF, ESI, TDS deductions, generate pay slips, and stay 100% compliant with labour laws.",
    gradient: "linear-gradient(135deg, #052E16, #166534)",
    topics: ["Salary Structuring", "PF & ESI Calculation", "TDS on Salary", "Professional Tax", "Payroll Software", "Labour Laws"],
    category: "Compliance",
  },
  {
    id: "c6",
    title: "Cost Accounting & Management",
    slug: "cost-accounting-management",
    badge: "ADVANCED",
    icon: TrendingUp,
    level: "Advanced",
    duration: "3 Months",
    price: 8999,
    originalPrice: 14000,
    rating: 4.9,
    reviewCount: 52,
    description: "Job costing, process costing, marginal costing — the analytical framework that drives C-suite decisions.",
    gradient: "linear-gradient(135deg, #0D4A26, #15803D)",
    topics: ["Job & Batch Costing", "Process Costing", "Marginal Costing", "Standard Costing", "Budgetary Control", "Variance Analysis"],
    category: "Advanced",
  },
  {
    id: "c7",
    title: "Audit & Internal Control Mastery",
    slug: "audit-internal-control-mastery",
    badge: "PROFESSIONAL",
    icon: ShieldCheck,
    level: "Advanced",
    duration: "6 Weeks",
    price: 6499,
    originalPrice: 10500,
    rating: 4.8,
    reviewCount: 77,
    description: "Design audit programs, execute internal audits, identify control gaps, and present board-ready audit reports.",
    gradient: "linear-gradient(135deg, #14532D, #22C55E)",
    topics: ["Audit Planning", "Internal Controls", "Vouching & Verification", "Statutory Audit", "Audit Reports", "Risk Assessment"],
    category: "Advanced",
  },
  {
    id: "c8",
    title: "SAP FICO for Finance Professionals",
    slug: "sap-fico-finance-professionals",
    badge: "ENTERPRISE",
    icon: Cpu,
    level: "Advanced",
    duration: "5 Months",
    price: 14999,
    originalPrice: 22000,
    rating: 4.9,
    reviewCount: 204,
    description: "The most in-demand ERP skill in corporate finance. Configure GL, AP, AR, Asset Accounting in SAP.",
    gradient: "linear-gradient(135deg, #052E16, #0D4A26)",
    topics: ["SAP Architecture", "General Ledger", "Accounts Payable", "Accounts Receivable", "Asset Accounting", "Bank Accounting"],
    category: "Advanced",
  },
  {
    id: "c9",
    title: "MCA & ROC Filing Compliance",
    slug: "mca-roc-filing-compliance",
    badge: null,
    icon: Landmark,
    level: "Intermediate",
    duration: "4 Weeks",
    price: 3999,
    originalPrice: 6500,
    rating: 4.7,
    reviewCount: 43,
    description: "Annual returns, AOC-4, MGT-7, DIN management — handle all MCA21 portal filings with precision.",
    gradient: "linear-gradient(135deg, #166534, #16A34A)",
    topics: ["Company Incorporation", "DIN & DSC Setup", "AOC-4 & MGT-7", "Board Resolutions", "Annual Returns", "XBRL Filing"],
    category: "Compliance",
  },
  {
    id: "c10",
    title: "Banking & Finance Operations",
    slug: "banking-finance-operations",
    badge: "NEW",
    icon: Banknote,
    level: "Beginner",
    duration: "3 Months",
    price: 6999,
    originalPrice: 11000,
    rating: 4.8,
    reviewCount: 56,
    description: "Credit appraisal, MSME lending, NPA management, KYC/AML compliance for banking sector careers.",
    gradient: "linear-gradient(135deg, #0D4A26, #22C55E)",
    topics: ["Retail Banking", "Corporate Lending", "KYC & AML Rules", "NPA Management", "Trade Finance", "Credit Appraisal"],
    category: "Accounting",
  },
  {
    id: "c11",
    title: "QuickBooks & Zoho Books",
    slug: "quickbooks-zoho-books",
    badge: null,
    icon: Monitor,
    level: "Beginner",
    duration: "3 Weeks",
    price: 2999,
    originalPrice: 4500,
    rating: 4.6,
    reviewCount: 88,
    description: "Cloud accounting for freelancers, startups, and SMEs. Master both platforms and offer a premium service.",
    gradient: "linear-gradient(135deg, #15803D, #22C55E)",
    topics: ["QuickBooks Setup", "Zoho Books Invoicing", "Expense Tracking", "Bank Sync", "Multi-currency", "Financial Reporting"],
    category: "Accounting",
  },
  {
    id: "c12",
    title: "CA Foundation Accelerator",
    slug: "ca-foundation-accelerator",
    badge: "POPULAR",
    icon: Award,
    level: "Beginner",
    duration: "6 Months",
    price: 11999,
    originalPrice: 18000,
    rating: 4.9,
    reviewCount: 315,
    description: "Bridge between graduation and CA exams. Accounting principles, law basics, quantitative aptitude, economics.",
    gradient: "linear-gradient(135deg, #052E16, #16A34A)",
    topics: ["Accounting Principles", "Business Laws", "Quantitative Aptitude", "Business Economics", "Mock Exams", "Study Planning"],
    category: "Accounting",
  }
];
